-- 2026-02-05: keep history (audit log) of acreencias changes
-- This enables showing explicit "antes → después" changes in /lista.

-- NOTE: In some databases `acreencias.id` is `uuid`, in others it is `bigint`.
-- This block detects the real column types and creates the history table with
-- compatible types so the FK + trigger inserts work.
DO $$
DECLARE
  id_type TEXT;
  proceso_id_type TEXT;
  apoderado_id_type TEXT;
  acreedor_id_type TEXT;

  existing_id_type TEXT;
  existing_proceso_id_type TEXT;
  existing_apoderado_id_type TEXT;
  existing_acreedor_id_type TEXT;
BEGIN
  SELECT format_type(a.atttypid, a.atttypmod)
  INTO id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'acreencias'
    AND a.attname = 'id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  SELECT format_type(a.atttypid, a.atttypmod)
  INTO proceso_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'acreencias'
    AND a.attname = 'proceso_id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  SELECT format_type(a.atttypid, a.atttypmod)
  INTO apoderado_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'acreencias'
    AND a.attname = 'apoderado_id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  SELECT format_type(a.atttypid, a.atttypmod)
  INTO acreedor_id_type
  FROM pg_attribute a
  JOIN pg_class c ON c.oid = a.attrelid
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname = 'public'
    AND c.relname = 'acreencias'
    AND a.attname = 'acreedor_id'
    AND a.attnum > 0
    AND NOT a.attisdropped;

  IF id_type IS NULL
     OR proceso_id_type IS NULL
     OR apoderado_id_type IS NULL
     OR acreedor_id_type IS NULL THEN
    RAISE EXCEPTION 'No se pudieron detectar los tipos de columnas de public.acreencias.';
  END IF;

  IF to_regclass('public.acreencias_historial') IS NOT NULL THEN
    SELECT format_type(a.atttypid, a.atttypmod)
    INTO existing_id_type
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'acreencias_historial'
      AND a.attname = 'acreencia_id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    SELECT format_type(a.atttypid, a.atttypmod)
    INTO existing_proceso_id_type
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'acreencias_historial'
      AND a.attname = 'proceso_id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    SELECT format_type(a.atttypid, a.atttypmod)
    INTO existing_apoderado_id_type
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'acreencias_historial'
      AND a.attname = 'apoderado_id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    SELECT format_type(a.atttypid, a.atttypmod)
    INTO existing_acreedor_id_type
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'public'
      AND c.relname = 'acreencias_historial'
      AND a.attname = 'acreedor_id'
      AND a.attnum > 0
      AND NOT a.attisdropped;

    IF existing_id_type IS DISTINCT FROM id_type
       OR existing_proceso_id_type IS DISTINCT FROM proceso_id_type
       OR existing_apoderado_id_type IS DISTINCT FROM apoderado_id_type
       OR existing_acreedor_id_type IS DISTINCT FROM acreedor_id_type THEN
      -- History is derived data: if the schema is incompatible, we recreate it.
      DROP TABLE public.acreencias_historial CASCADE;
    END IF;
  END IF;

  EXECUTE format($sql$
    CREATE TABLE IF NOT EXISTS public.acreencias_historial (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      acreencia_id %1$s NOT NULL REFERENCES public.acreencias(id) ON DELETE CASCADE,
      proceso_id %2$s NOT NULL,
      apoderado_id %3$s NOT NULL,
      acreedor_id %4$s NOT NULL,
      operacion TEXT NOT NULL CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE')),
      changed_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      changed_by UUID,
      old_data JSONB,
      new_data JSONB
    );
  $sql$, id_type, proceso_id_type, apoderado_id_type, acreedor_id_type);
END $$;

CREATE INDEX IF NOT EXISTS idx_acreencias_historial_proceso_changed_at
  ON public.acreencias_historial (proceso_id, changed_at DESC);

CREATE INDEX IF NOT EXISTS idx_acreencias_historial_acreencia_changed_at
  ON public.acreencias_historial (acreencia_id, changed_at DESC);

CREATE OR REPLACE FUNCTION public.log_acreencias_historial()
RETURNS TRIGGER AS $$
BEGIN
  IF (TG_OP = 'INSERT') THEN
    INSERT INTO public.acreencias_historial (
      acreencia_id, proceso_id, apoderado_id, acreedor_id,
      operacion, changed_at, changed_by, old_data, new_data
    )
    VALUES (
      NEW.id, NEW.proceso_id, NEW.apoderado_id, NEW.acreedor_id,
      'INSERT', NOW(), auth.uid(), NULL, to_jsonb(NEW)
    );
    RETURN NEW;
  ELSIF (TG_OP = 'UPDATE') THEN
    INSERT INTO public.acreencias_historial (
      acreencia_id, proceso_id, apoderado_id, acreedor_id,
      operacion, changed_at, changed_by, old_data, new_data
    )
    VALUES (
      NEW.id, NEW.proceso_id, NEW.apoderado_id, NEW.acreedor_id,
      'UPDATE', NOW(), auth.uid(), to_jsonb(OLD), to_jsonb(NEW)
    );
    RETURN NEW;
  ELSIF (TG_OP = 'DELETE') THEN
    INSERT INTO public.acreencias_historial (
      acreencia_id, proceso_id, apoderado_id, acreedor_id,
      operacion, changed_at, changed_by, old_data, new_data
    )
    VALUES (
      OLD.id, OLD.proceso_id, OLD.apoderado_id, OLD.acreedor_id,
      'DELETE', NOW(), auth.uid(), to_jsonb(OLD), NULL
    );
    RETURN OLD;
  END IF;

  RETURN NULL;
END;
$$ language 'plpgsql';

ALTER FUNCTION public.log_acreencias_historial() SECURITY DEFINER;
ALTER FUNCTION public.log_acreencias_historial() SET search_path = public;

DROP TRIGGER IF EXISTS acreencias_historial_insert ON public.acreencias;
CREATE TRIGGER acreencias_historial_insert
  AFTER INSERT ON public.acreencias
  FOR EACH ROW EXECUTE FUNCTION public.log_acreencias_historial();

DROP TRIGGER IF EXISTS acreencias_historial_update ON public.acreencias;
CREATE TRIGGER acreencias_historial_update
  AFTER UPDATE ON public.acreencias
  FOR EACH ROW EXECUTE FUNCTION public.log_acreencias_historial();

DROP TRIGGER IF EXISTS acreencias_historial_delete ON public.acreencias;
CREATE TRIGGER acreencias_historial_delete
  AFTER DELETE ON public.acreencias
  FOR EACH ROW EXECUTE FUNCTION public.log_acreencias_historial();

ALTER TABLE public.acreencias_historial ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'acreencias_historial'
      AND policyname = 'Allow all for authenticated users'
  ) THEN
    CREATE POLICY "Allow all for authenticated users" ON public.acreencias_historial
      FOR ALL
      TO authenticated
      USING (true)
      WITH CHECK (true);
  END IF;
END $$;
